services:
  db:
    image: postgres:16
    container_name: sdlc-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sdlc_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - sdlc_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: sdlc-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
  api:
    build: .
    container_name: sdlc-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  sdlc_db_data:
